### ISSUE TITLE
Error on Statistics View

### ISSUE THREAD

**Issue by euroacad** [mindshape-GmbH/mindshape_cookie_consent#1]
I get the following message while clicking on statistics view:

Oops, an error occurred!
No site found for identifier §§§ALL_SITES§§§
More information regarding this error might be available online.

Please help.

**Comment by featdd** [comment]
Hi @euroacad,

thanks for the hint, I found and solved the issue, see: 0501194f050e28896e3f442f2afb197c28997531

Greetings
Daniel

**Comment by msollmann** [comment]
Hi @featdd,

your fix in Classes/Controller/Backend/StatisticController.php uses a query on table sys_language which is not existing in TYPO3 12 (anymore):
"An exception occurred while executing a query: Table 'sys_language' doesn't exist"

And why is "$site instanceof Site" (line 296) false? Did I misconfigure something or is it a bug?
