### ISSUE TITLE
 Error with frontend_editing

### ISSUE THREAD

**Issue by quadronet** [mindshape-GmbH/mindshape_cookie_consent#10]
Hello, 
we use the frontend_editing and get the following error:

(1/1) TypeError
array_key_exists() expects parameter 2 to be array, null given

in /var/www/vhosts/photos/domain.de/typo3conf/ext/mindshape_cookie_consent/Classes/Utility/SettingsUtility.php line 61
        try {
            $typoscript = $configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
            $typoscript = GeneralUtility::removeDotsFromTS($typoscript);

            if (false === array_key_exists(self::EXTENSION_TYPOSCRIPT_KEY, $typoscript['plugin'])) {

**Comment by featdd** [comment]
Hi @quadronet,

I couldn't reproduce this when using frontend editing, seems like an issue in your configuration.
Nevertheless I secured the condition to prevent this exception.

Solved in b19a1bd2f51faacbcb89344d0d032fda5c6779e1
