### ISSUE TITLE
only one button when all cookies are necessary

### ISSUE THREAD

**Issue by chrishap21** [mindshape-GmbH/mindshape_cookie_consent#11]
Hi,

when there are only necessary cookies it would be nice if there was only one button like 'Okay' instead of both of the 'Select all' AND 'Save' buttons.

This would be helpful if you start with a simple set of cookies, adding further choices later on in your TYPO3.

Best regards

ch

**Comment by featdd** [comment]
Hi @chrishap21,

this makes sense, I added this as the new default behaviour.

Solved in 56d61c73ff31dec2610773f5d8f5dfc48c53aedb
