### ISSUE TITLE
Consent is not visible having multiple root pages

### ISSUE THREAD

**Issue by cgo123** [mindshape-GmbH/mindshape_cookie_consent#13]
![image](https://user-images.githubusercontent.com/43548448/116978033-140a1900-acbb-11eb-9527-fa0029714542.png)

Banner erscheint nicht bei 2. Root Seite, bitte um Hilfe

**Comment by featdd** [comment]
Hi @cgo123,

please create issues in english.

Did you create two seperate configurations for each domain or do you have one configuration for both domains?

Greetings
Daniel

**Comment by cgo123** [comment]
On the 2nd page the stylesheet was forgotten. Works now. Thanks
