### ISSUE TITLE
TCA points to non-existent field label

### ISSUE THREAD

**Issue by neufeind** [mindshape-GmbH/mindshape_cookie_consent#16]
The TCA for tx_mindshapecookieconsent_domain_model_statisticbutton, tx_mindshapecookieconsent_domain_model_statisticcategory and tx_mindshapecookieconsent_domain_model_statisticoption points to a non-existent field "label".

On one TYPO3-installation at DB-comparison this resulted in SQL-errors where TYPO3 tried to query that field. Commenting out the "label"-row from TCA made it work again.

[...]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `uid`, `pid`, `label` FROM `tx_mindshapecookieconsent_domain_model_statisticbutton` WHERE ...

**Comment by featdd** [comment]
Hi @neufeind,

strange... I never encountered this issue.
I adjusted the label field to just use the beginning date as the record is hidden for the list module anyway.

See: 56f5ef4a7cff617be75bfad0123bc77bc27de889

Greetings
Daniel

**Comment by neufeind** [comment]
Thanks for the quick fix. Noticed it with a TYPO3 v9.x, maybe didn't show in other TYPO3-versions. Haven't seen such errors in other installations. But it still wasn't logical :-)
