### ISSUE TITLE
Only display consent if activated

### ISSUE THREAD

**Issue by klodeckl** [mindshape-GmbH/mindshape_cookie_consent#17]
The consent is already shown if the extension is installed. It would be great if the admin has to activate or include the typoscript first.

**Comment by featdd** [comment]
Hi @klodeckl,

the extension creates a basic configuration for any existing site during the installation.
This is intended as a help for unexperienced integrators.

You can still deactivate or delete configurations to disable the consent modal for a site, so I currently don't see the necessity for a seperate switch to explicitly enable/disable it.

Greetings
Daniel
