### ISSUE TITLE
fire if event cookieConsent on load

### ISSUE THREAD

**Issue by derBoogie** [mindshape-GmbH/mindshape_cookie_consent#18]
Hi,
I thought that the event cookieConsent also fires on load, so that you can check the status of previously set cookies.
How else can I check via JavaScript which cookies have been set?

**Comment by featdd** [comment]
HI @derBoogie,

how do you mean this exactly?

The event will only be triggered on load if a consent cookie already exists.
Otherwise the the event will be triggered after the user submits the consent in the modal form.

You may also have a look into the [official documentation](https://docs.typo3.org/p/mindshape/mindshape-cookie-consent/1.2/en-us/).

Greetings
Daniel

**Comment by derBoogie** [comment]
Hi Daniel,

in my cookie-consent.js, which is loaded on every page I have:
```
$(document).ready(function() {

  window.googleAnalyticsLoaded = false;
  window.addEventListener('cookieConsent', function (event)
  {
    if (event.detail.hasOption('google_analytics'))
    {
      if (false === window.window.googleAnalyticsLoaded)
      {
        window.googleAnalyticsLoaded = true;
        console.log('Load Google Analyitcs');
      }
    }
  });

});
```
In console I can see "Load Google Analyitcs" if I accept the google_analtics cookie (check checkbox and save), which works fine.
But when I continue surfing the page, "Load Google Analyitcs" is not displayed in the console. I.e. on load the cookie_consent event is not fired.
Here you can see the value of cookie "cookie_consent":
![grafik](https://user-images.githubusercontent.com/1611217/127278002-2e933ff2-2cae-4ed9-8230-a4c057e2b056.png)

Greetings
TJ

**Comment by featdd** [comment]
Hi @derBoogie,

You have to implement the explicit loading of analytics or other tools by yourself, the extension just offers you the consent mechanics, analytics ist just meant as an example in the documentation.

You may want to have a look at an [concrete example](https://github.com/mindshape-GmbH/mindshape_seo/blob/v2.0.1/Resources/Private/Templates/Analytics/GoogleAnalyticsCookieConsent.html), this loads Google Analytics Universal if the user consented to.

Greetings
Daniel

**Comment by derBoogie** [comment]
Hi Daniel,

thanks for your quick reply.

I've already implemented an own solution for the "on load mechanism" of cookies which are allowed by th user.
That means, which are stored in the cookie_consent cookie.

In my opinion this should be part of your extension, because It's an essential feature.

Greetings
TJ

**Comment by featdd** [comment]
Hi @derBoogie,

the mechanism is already there, I don't know why you did your own, see the link to the example I posted earlier.

The extension doesn't automaticely block any scripts or something, it provides the functionality to load your analytics (google, matomo or whatever) only if the user consented.

Greetings
Daniel
