### ISSUE TITLE
Check multiple same cookies in the details view

### ISSUE THREAD

**Issue by kveldscholten** [mindshape-GmbH/mindshape_cookie_consent#2]
Hello

Matomo uses two cookies (_pk_id.WebsiteID.DomainHash, _pk_ses.WebsiteID.DomainHash) but in the detailed view I can check the cookies individually.

I would like that if check a Matomo cookie, it will automatically both cookies.

I tried the same identifier but it only hacked the first one.

![mindshape_cookie_consent_matomo](https://user-images.githubusercontent.com/5719257/91148290-b815dc00-e6b9-11ea-8df0-876762d1b6cd.jpg)

**Comment by featdd** [comment]
Hi @kveldscholten,

you could solve that with javascript manually.

But I would just recommend to use one cookie information for Matomo and mention the seperate cookies in the cookie name field.
Google Analytics etc. also can have multiple physical cookies, but in the example it is mentioned as "one cookie".

You may consult your datapolicy lawyer for further advise.

Greetings
Daniel

**Comment by kveldscholten** [comment]
Okay i have solve it with javascript and same data-identifier.

```
window.addEventListener('cookieConsent', function (event) {
    $(document).on('click', 'input[type="checkbox"][data-identifier]', function (event) {
        var actor = $(this),
            checked = actor.prop('checked'),
            identifier = actor.data('identifier'),
            checkboxes = $('input[type="checkbox"][data-identifier="' + identifier + '"]'),
            otherCheckboxes = checkboxes.not(actor);

        otherCheckboxes.prop('checked', checked);
    });
});
```
