### ISSUE TITLE
Can't overwritte language labels with typoscript 

### ISSUE THREAD

**Issue by giesenmartin** [mindshape-GmbH/mindshape_cookie_consent#20]
I tried it with the key which seems corectly for me.

plugin.tx_mindshapecookieconsent_consent {
  _LOCAL_LANG.de {
      label { 
        imprint = Database
        necessary_cookies = Database
      }
  }
}

I try also this

plugin.tx_mindshapecookieconsent {
  _LOCAL_LANG.de {
      label { 
        imprint = Database
        necessary_cookies = Database
      }
  }
}

But nothings works for me.  
How to write it correctly.

Greetings 
Martin

**Comment by featdd** [comment]
Hi @giesenmartin,

I think you're refering to the deprecated "[mindshape_cookie_hint](https://github.com/mindshape-GmbH/mindshape_cookie_hint)" extension, this is the repository of the new extension "mindshape_cookie_consent".

Please habe a look at the [correct documentation](https://docs.typo3.org/p/mindshape/mindshape-cookie-consent/1.2/en-us/).

If you want to alter translations with custom labels have a look at the [core documentation](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Internationalization/ManagingTranslations.html#custom-translations).
To see what labels are used in this extension have a look [here](https://github.com/mindshape-GmbH/mindshape_cookie_consent/blob/master/Resources/Private/Language/locallang.xlf).

Greetings
Daniel
