### ISSUE TITLE
Translations not working / not usefull for multilang sites

### ISSUE THREAD

**Issue by 22markets** [mindshape-GmbH/mindshape_cookie_consent#26]
Can't overwritte language labels with typoscript #20 

this problem is not solved and the problem with the translated version (button / texts) is also not solved. So it is not working in multilanguage sites

**Comment by featdd** [comment]
Hi @22markets,

have you used the latest way for [custom translations](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Internationalization/ManagingTranslations.html#custom-translations) as refered in #20!?

As far as I know translations in TypoScript are not that favoured anymore. (correct me if I'm wrong)

Greetings
Daniel

**Comment by 22markets** [comment]
Hello Daniel,

I have tried to use the translation fields from the extension in the backend and the fields for the cookie groups and cookies in the located version. But the translated contents are not visible in version 2.0 and above. Only the values from the default language. Also the strings for necessary cookies and the deny buttons have no fields in the backend to be translated 

Mit freundlichen Grüßen

Sebastian Lorenz








Langheimer Str. 60  --||--  D-96264 Altenkunstadt

fon:		+49 9572-8729002
mobil:	+49 172-8614459
email: 	***@***.***

**Comment by featdd** [comment]
Hi @22markets,

could you update the extension (2.1) and your TYPO3 instance to its latest versions and verify this still doesn't work?

I will try consider adding a custom label field for the deny button for the next update.

How did you add your custom translations, as explained in the documentation? Did you create a proper XLIFF file?
Maybe have another look or please submit a bit more details of your implentation.

Greetings
Daniel

**Comment by SimonWpt** [comment]
Second problem: I can't edit the necassary cookie.

![image](https://user-images.githubusercontent.com/160817/153586681-2c234dfb-5d71-4357-8fe9-2d46c65a5393.png)

Working with ddev, TYPO3 10.4.23 and mindshape_cookie_consent 2.1.2.

**Comment by stephangrass** [comment]
Same problems here ...

**Comment by featdd** [comment]
> Hi @featdd,
> 
> thanks, it really looks like it works in the frontend.
> 
> But in the backend the error 
> `Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()`
> appears if you want to edit the consent configuration.
> 
> My TYPO3 10.4.24 installation is not based on composer ...

Have you installed the latest TYPO3 v10?

**Comment by featdd** [comment]
HI @stephangrass,

the issue is caused by the none composer installation, I have a composer installation wich provides a forward compatibility package with the methods used in v11.

I replaced all methods with the proper v10 variants, see: 88de993745df4fb39133e2c091568230a90668d7

May you have another try?
I will try to release an Update next week.

Greetings
Daniel

**Comment by stephangrass** [comment]
Hi @[featdd](https://github.com/featdd)

thanks a lot!
Unfortunately, I have some installations that cannot be switched to Composer for various reasons. And I guess I'm not the only one with this...

But there is still one more place where fetchAllAssociative() is used:

`Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()
in /Users/stephangrass/Documents/_Webs_/kirchhoff-mobility.com/typo3/www/typo3conf/ext/mindshape_cookie_consent/Classes/UserFunc/ConfigurationTcaUserFunc.php line 61`

Greetings
Stephan

**Comment by featdd** [comment]
@stephangrass have you checked out the correct commit?

I amended the changes to the bugfix commit, see this commit: 85c38de8d2f9325f683a0f4b4821b4f1426468fc

**Comment by stephangrass** [comment]
Argh, ok. Thanks. I will try it later.

nice weekend
Stephan

**Comment by stephangrass** [comment]
Moin Daniel,
thanks a lot, it looks really good now.

Stephan

**Comment by featdd** [comment]
@stephangrass @SimonWpt @22markets Update 2.1.3 with this fix is available in TER
