### ISSUE TITLE
Different Cookies per Language

### ISSUE THREAD

**Issue by stephangrass** [mindshape-GmbH/mindshape_cookie_consent#29]
Hi.
I have to set an own cookie in one language version of the website. That's why I created a cookie in this language that only exists here. I now hoped that the consent banner would be displayed again when the language was changed, even if it had already been used in the default language.

Is something like that even possible?

Thanks
Stephan

**Comment by featdd** [comment]
Hi @stephangrass,

not yet, you can only change the cookie name to force show the updated consent for the users.

It would be an interesting feature anyway, so I would handle this as a feature request.
I will just need time and thoughts to implement this.

Greetings
Daniel

**Comment by stephangrass** [comment]
That would be great. We also use the language selection for "country representation pages". E.g. German/Germany, German/Switzerland, French/Switzerland. And one country representation wants to track, the other doesn't.

**Comment by featdd** [comment]
Hi @stephangrass,

next to change the cookie name for each language via TypoScript you can now integrate languages into one consent cookie.

Solved in: 40e83bab8da4f0827321308e287c887d343ebeba

Greetings
Daniel
