### ISSUE TITLE
Disable load googleAnalytics and piwik from cs_seo plugin

### ISSUE THREAD

**Issue by kveldscholten** [mindshape-GmbH/mindshape_cookie_consent#3]
Hello

i have a feature request

i use the cs_seo plugin for seo analyse and to add Google Analytics and Piwik.

If I am informed correctly then I could load the code manually (event.detail.hasOption('google_analytics')) with your Cookie Consent or not but what about the integration through the plugin cs_seo.

Will there be a possibility not to load Google Analytics and Piwik there?

Here see how cs_seo add analytics code
https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/Tracking/googleAnalytics.typoscript
https://github.com/clickstorm/cs_seo/blob/master/Configuration/TypoScript/Setup/Tracking/piwik.typoscript

**Comment by featdd** [comment]
Hi @kveldscholten,

you just have to wrap the analytics javascript inside the event listener just like in the example in the documentation.

I cannot provide you support for an external extension but as it looks their analytics is just injected via typoscript, so you should be able to override their default with one containing the event listener to prevent loading analytics before checking the consent of the user.

Greetings
Daniel
