### ISSUE TITLE
Preselection

### ISSUE THREAD

**Issue by SimonWpt** [mindshape-GmbH/mindshape_cookie_consent#30]
One customer wishs, that the Cookies are preselected. I can't find an entry for this. Is this feature not implemented?

![image](https://user-images.githubusercontent.com/160817/156572070-294fa8c0-3d44-4be9-8681-e8dd7127fcd0.png)

**Comment by featdd** [comment]
Hi @SimonWpt,

this shouldn't be possible as this would be not conform to GDPR.
You could still do this in the template but you should talk to a datapolicy lawyer first.

Greetings
Daniel
