### ISSUE TITLE
denyLabel not available in Configuration

### ISSUE THREAD

**Issue by TBschen** [mindshape-GmbH/mindshape_cookie_consent#31]
configuration.denyLabel is being checked in Form.html, but outside of that it is nowhere to be found.
It should be implemented though, as the other labels already are. Needs changes in a few files and a new database field.

I've attached the customized extension - works for me. You can check if there's something missing.

[mindshape_cookie_consent_2.1.4.1_202204271322.zip](https://github.com/mindshape-GmbH/mindshape_cookie_consent/files/8572386/mindshape_cookie_consent_2.1.4.1_202204271322.zip)

**Comment by featdd** [comment]
Hi @TBschen,

this is solved in beccea99908f1561dff976936dd27448e60252ab

Greetings
Daniel
