### ISSUE TITLE
Google Consent Mode [Feature Request]

### ISSUE THREAD

**Issue by mikeemike7** [mindshape-GmbH/mindshape_cookie_consent#34]
Google Consent Mode Integration (Feature Request)

Hi, it would be nice (essential for comercial use) to have a tracking without consent.
When do you support google consent mode?
Greets from Münster, M.

**Comment by featdd** [comment]
Hi @mikeemike7,

I what do you mean exactly?
You still have to add the script for Google Analytics etc. by yourself, therefore you would be able to adjust the integration as you like.

As I'm understanding [THIS](https://support.google.com/analytics/answer/9976101?hl=en) right you would always load analytics but with denied consent by default like this:

```
<script async src="//www.googletagmanager.com/gtag/js?id={analyticsId}" data-ignore="1"></script>
<script data-ignore="1">
  window.dataLayer = window.dataLayer || [];

  function gtag() { dataLayer.push(arguments) }

  gtag("consent", "default", { ad_storage: "denied", analytics_storage: "denied" });

  gtag('js', new Date());
  gtag('config', '<f:format.raw>{analyticsId}</f:format.raw>', { 'anonymize_ip': true });
</script>
```

Then you could add the consent event to update the consent mode:

```
<script data-ignore="1">
  window.cookieConsentLoadedGoogleAnalytics = false;
  window.addEventListener('cookieConsent', function (event) {
    if (
      false === window.cookieConsentLoadedGoogleAnalytics &&
      event.detail.hasOption('google_analytics')
    ) {
      gtag("consent", "update", { ad_storage: 'granted', analytics_storage: 'granted' });
    }
  });
</script>
```

But honestly I'm not sure about the legal safety, as I can't give you legal information you should still consultate your privacy lawyer for this.

When I'm currently integrating a consent I completely withhold the loading of the external scripts to be safe there, like this:

```
<script data-ignore="1">
  window.cookieConsentLoadedGoogleAnalytics = false;
  window.addEventListener('cookieConsent', function (event) {
    if (
      false === window.cookieConsentLoadedGoogleAnalytics &&
      event.detail.hasOption('google_analytics')
    ) {
      let script = document.createElement('script');

      script.async = true;
      script.src = '//www.googletagmanager.com/gtag/js?id=UA-XXXXXX-XX';

      document.head.appendChild(script);

      window.cookieConsentLoadedGoogleAnalytics = true;
      window.dataLayer = window.dataLayer || [];
      function gtag() {dataLayer.push(arguments)}
      gtag('js', new Date());
      gtag('config', 'UA-XXXXXX-XX', { 'anonymize_ip': true });
    }
  });
</script>
```

Overall this looks more like an individual legal question to me rather then an adjustment/feature for this extension...
I hope this answer still helps you out.

Merry christmas
Daniel

**Comment by mikeemike7** [comment]
Hi Daniel,
many thanks for your detailed response. It was a technical question, not a legal one*.
The Problem for Google Ads-Customers is, not every user is willing to give consent. The annoying banner is just clicked away so that it's not possible to measure the success of your Ads. 
I supposed, the Consent Mode-Api might be a good idea: if I understood that correctly, the Google Consent Mode provides no personal data, just aggregated data with - so performance measurement could also be possible without consent and without setting of cookies. In that case it could at least be enough to evaluate the success of an Ads campaign.
*But I think you are right - from a legal point of view still servers in the USA are contacted - without consent...
Merry Christmas
Mikee
