### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by paulilea** [mindshape-GmbH/mindshape_cookie_consent#40]
The latest version can't be installed via composer for PHP 8.2.x (x>0).
Is there a reason why the extension is set to only be compatible with PHP up to and including 8.2.0?
Is it just a typo, `"php": "~8.0 <=8.2"` instead of `"php": "~8.0 <8.3"`?

**Comment by featdd** [comment]
Hi @paulilea,

I couldn't really reproduce this.
I'm using PHP 8.2.7 with composer 2.5.8 and could install the extension from packagist.

The require entry in my composer.json `"mindshape/mindshape-cookie-consent": "~3.0"`.

For my understanding both expressions are valid and mean the same, so the extension should be installable with PHP 8.0.x | 8.1.x | 8.2.x

Can you please check your composer output again or paste some debug information for me!?

Greetings
Daniel

**Comment by paulilea** [comment]
Hi @featdd,

This is the output from composer:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mindshape/mindshape-cookie-consent ~3.0 -> satisfiable by mindshape/mindshape-cookie-consent[v3.0.0].
    - mindshape/mindshape-cookie-consent v3.0.0 requires php ~8.0 <=8.2 -> your php version (8.2.7) does not satisfy that requirement.
```
So it seems that '<=8.2' is evaluted to '<=8.2.0'.
 
It can be prevented by adding something like this to my composer.json:
```
"config": {
  "platform": {
    "php": "8.2"
  }
}
```
But, in general, I don't want to do this because it can affect the other dependencies of the project.
