### ISSUE TITLE
Statistics - selected time period throws exeption

### ISSUE THREAD

**Issue by DTM-TYPO3** [mindshape-GmbH/mindshape_cookie_consent#41]
Hello,

I`m using the statistics module of mindshape_cookie_consent. When I change the time period in die select-field above, an exception is thrown saying:

> Call to undefined method TYPO3\CMS\Backend\Template\ModuleTemplate::assign()

in mindshape_cookie_consent/Classes/Controller/Backend/StatisticController.php

Also the pagination doesn´t work. When clicking forward through the pages, it jumpes back to the initial selection.

Tested on Typo3 11.5.28 with PHP 8.1 and mindshape_cookie_consent 3.0.1

Thanks in advance.
Stefanie

**Comment by featdd** [comment]
Hi @DTM-TYPO3,

thankts for the hint, I could fix the exception here: 33317f04a0c85fea33ca2d8a4d683f6b50ffe677

But I struggle reproduce the issue with the pagination, have you overriden the backend templates?
The extension uses "georgringer/numbered-pagination" for the cropped pagination.

Greetings
Daniel

**Comment by DTM-TYPO3** [comment]
Hi @featdd,
thanks for the quick fix. Changing the time periods is working now.

As for pagination, I´ve not changed any templates and the EXT numbered-pagination is installed in version 1.0.5 (latest, also tested with TER V1.0.2). Nevertheless, it jumpes back to the initial selection of the module.

Btw. there is no hint in dependencies in mindshape_cookie_consent that the EXT is required.

Regards
Stefanie

**Comment by featdd** [comment]
Hi @DTM-TYPO3,

sorry for the late response, do you use a non composer instance for your TYPO3?
That might be the issue, I declared the missing dependency in the ext_emconf here: c66cd747d635b792e666267ab1cdf8ceba130924

Greetings
Daniel

**Comment by featdd** [comment]
Hi @DTM-TYPO3,

an update with this fix is now released in TER.

Greetings
Daniel
