### ISSUE TITLE
Plugin prevents Caching

### ISSUE THREAD

**Issue by tgriessbach** [mindshape-GmbH/mindshape_cookie_consent#45]
Hello everyone,
we use TYPO3 v11.5.30 and mindshape_cookie_consent v3.0.1
installed with composer following the documentation: 
https://docs.typo3.org/p/mindshape/mindshape-cookie-consent/main/en-us/Index.html

If we activate 
`plugin.tx_mindshapecookieconsent.settings.addMarkupToFooter = 1`
the caching for that page is disabled.

Problem seems to be the config in ext_localconf.php 

```
ExtensionUtility::configurePlugin(
    SettingsUtility::EXTENSION_KEY,
    'Consentmodal',
    [ConsentController::class => 'modal'],
    [ConsentController::class => 'modal'],
ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
);
```

If I remove the action from $nonCacheableControllerActions like this:

```
ExtensionUtility::configurePlugin(
    SettingsUtility::EXTENSION_KEY,
    'Consentmodal',
    [ConsentController::class => 'modal'],
    [],
    ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
);
```

then the page is cached correctly.

The same problem seems to occur if we put a ContentElement of CType mindshapecookieconsent_consent on a page.

In v2.2.5 the caching worked...

Is this a known bug or a configuration mistake?

**Comment by wrock** [comment]
Same problem here...

**Comment by daeff** [comment]
Similar problem here with INTincScript

We've got a TYPO3 12.4.7
with mindshape/mindshape-cookie-consent:3.0.1 
along with lochmueller/staticfilecache:13.1.3

Staticfilecache is not able to cache anything because of the uncached Plugins 

```
…

        ExtensionUtility::configurePlugin(
            SettingsUtility::EXTENSION_KEY,
            'Consent',
            [ConsentController::class => 'settings,consent,renderConsentModal'],
            [ConsentController::class => 'settings,consent,renderConsentModal'],
            ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
        );

        ExtensionUtility::configurePlugin(
            SettingsUtility::EXTENSION_KEY,
            'Consentmodal',
            [ConsentController::class => 'modal'],
            [ConsentController::class => 'modal'],
            ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
        );
 …
```

**Comment by featdd** [comment]
Hi @tgriessbach @wrock @daeff,

sorry for the problems I will try to fix this soon.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @tgriessbach @wrock @daeff,

sorry for the late replys, solved this here now: edbb5b0ad884e3132a9969ac9c842fdcfae95512

Greetings
Daniel

**Comment by tgriessbach** [comment]
Hi @featdd ,
thank you this fix seems to work!
Do you know when the next tag will be released?

**Comment by tgriessbach** [comment]
Thank you!
