### ISSUE TITLE
Missing neccessary cookies in "Cookie List"

### ISSUE THREAD

**Issue by gf-luka** [mindshape-GmbH/mindshape_cookie_consent#46]
The "Cookie List"-Plugin does not list the neccessary cookies. It only shows the *custom* categories and their cookies. I think the neccessary cookies should also be be listed.

Best regards, Gianni

**Comment by featdd** [comment]
Hi @gf-luka,

sorry this took a bit longer than I said but I solved this now here: 15442abce16931460833f783a78d2308d21e0b45

Greetings
Daniel
