### ISSUE TITLE
TypeError in List View, TYPO3 12.4.9

### ISSUE THREAD

**Issue by jungedigitale** [mindshape-GmbH/mindshape_cookie_consent#47]
After switching from TYPO3 version 12.4.8 to 12.4.9 we get a TypeError after accessing List view to the Page, where the Cookie Config ist stored:

Mindshape\MindshapeCookieConsent\UserFunc\ConfigurationTcaUserFunc::sitesItemsProcFunc(): Argument #2 ($tcaSelectItems) must be of type TYPO3\CMS\Backend\Form\FormDataProvider\TcaSelectItems, TYPO3\CMS\Core\DataHandling\ItemProcessingService given

in [...]/vendor/mindshape/mindshape-cookie-consent/Classes/UserFunc/ConfigurationTcaUserFunc.php line 44

Thanks & best regards
-Markus

**Comment by featdd** [comment]
Hi @jungedigitale,

I have to test this, haven't done the newest update yet.
Have you done some changes to the TCA of this extension? Otherwise this might be a breaking change in the core or something.

Greetings
Daniel

**Comment by jungedigitale** [comment]
Hi Daniel, 
thanks for the fast reply! No we haven't done any changes to the TCA of this extension, it is a standard implementation.

thanks & best regards
-Markus

**Comment by LimeUwe** [comment]
I have the same problem here.
Looking at the paramters, there is a unuserd parameter ```tcaSelectItems``` which is not of the correct type:

`public function sitesItemsProcFunc(array $parameters, TcaSelectItems $tcaSelectItems): void`

It's not user anywhere in the method, so I think it can be removed? List view works afterwards.

**Comment by birgitberlin** [comment]
I can confirm this problem.

**Comment by featdd** [comment]
Hi @jungedigitale, @LimeUwe, @birgitberlin,

I just pushed a commit that should fix the problem: 2bd7bfd9c3e15249b0fc567a16ed802c0b377dda
Can you guys confirm me this also works for you?

I don't know if this counts as a breaking change but this will break some peoples code, will have to check some other extensions later too...
Luckily in this case the parameter was unused anyway and just there for completion, so I could just remove it.

I will try to push an update to TER next week.

Greetings
Daniel

**Comment by jungedigitale** [comment]
Hi @featdd,
Thank you, the fix seems to have eliminated the issue!
best -Markus

**Comment by featdd** [comment]
Hi @jungedigitale, @LimeUwe, @birgitberlin,

I just pushed an update to TER containing this bugfix.

Greetings and merry christmas
Daniel

**Comment by jungedigitale** [comment]
Thank you very much for your work & happy new year!
