### ISSUE TITLE
TYPO3 12 CSP settings

### ISSUE THREAD

**Issue by emileblume** [mindshape-GmbH/mindshape_cookie_consent#48]
The inline script <script data-ignore="1"> is being blocked by the Content Security Policy in TYPO3 12.4.9. Unsafe inline can't be used when the nonce option is used.

**Comment by featdd** [comment]
Hi @emileblume,

updating the assets injection to using the newer asset collector should to the trick.
Can you give me feedback if this worked for you too?

Solved here: 51ee94125f6ce77e4e9925cd26d4162344066ba0

Greetings
Daniel

**Comment by featdd** [comment]
Hi @emileblume,

even though you found a workaround as mentioned here: https://github.com/mindshape-GmbH/mindshape_cookie_consent/commit/51ee94125f6ce77e4e9925cd26d4162344066ba0#commitcomment-135558997 this should be the preferable solution, so thanks anyway for the hint.

I'll keep this and prepare a new TER update in the new year, then you can update as you like.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @emileblume,

I just published a new update to TER.

Greetings
Daniel

**Comment by emileblume** [comment]
@featdd That's great, thanks!
