### ISSUE TITLE
PHP Warning: Undefined array key "site" in `Classes/UserFunc/ConfigurationTcaUserFunc.php` line 46 with TYPO3 12.4.10

### ISSUE THREAD

**Issue by mkempe** [mindshape-GmbH/mindshape_cookie_consent#49]
Hi,

after switching from TYPO3 version 12.4.9 to 12.4.10 we get a TypeError in the backend when using the list view. 

I think the problem is, that the passed `$parameters` changed with the new version. `$parameters['row']` does not contain the `site` and `sys_language_uid` anymore. Instead `$parameters['site']` contains now a site object.

PS: Many thanks for the extension and the maintenance of it.

**Comment by featdd** [comment]
Hi @mkempe,

thanks for the hint, I'll have to test this myself.
Maybe TYPO3 introduced another breaking change here, not the only one in the last time...

Greetings
Daniel

**Comment by mkempe** [comment]
Hey @featdd,

many thanks for looking into it. I also think it's bad, maybe they roll it back and we're waiting for the next release.

Have a nice week.

**Comment by featdd** [comment]
Hi @mkempe,

this really seems to be a core issue, I created a [ticket on forger](https://forge.typo3.org/issues/102847) for this.
Maybe this will get fixed quick so I'll wait a few days or release a workaround later.

Greetings
Daniel

**Comment by mkempe** [comment]
Hi @featdd,

hope I'm not disturbing you. Have you heard anything new about the issue? Unfortunately, the bug has not yet been fixed in the latest security release.

**Comment by featdd** [comment]
Hi @mkempe,

yes there is still no fix to the issue. (you can see the progress [here](https://forge.typo3.org/issues/102847))
I'll probably have to look for a workaround, give me some time to look for it.

Greetings
Daniel

**Comment by abvdveen** [comment]
Any news on this?

**Comment by featdd** [comment]
Hi @abvdveen & @mkempe,

sorry for the long waiting, initially hoped to get this fixed faster in the core, due to backwards incompatibility.
I just implemented a workaround, I would be happy to hear your feedback before an official release.

See: eff68e44c47b51c6c74d8052c668cd09a0631742

Greetings
Daniel

**Comment by abvdveen** [comment]
Looks ok to me. No errors anymore, everything seems to be working fine.

**Comment by mkempe** [comment]
Hi @featdd,

many thanks for taking the time to workaround a bug in core. I have tested the changes with the current version (`12.4.13`). Everything works as before. Thanks again.

**Comment by featdd** [comment]
Hi @abvdveen & @mkempe,

I just released an update (3.2.0) for packagist & TER with the workaround.

I'll leave this issue open as a reminder to fix this properly once the core bug is solved.

Greetings
Daniel

**Comment by mkempe** [comment]
Hi @featdd,

many thanks for the new release. Have a great day.
