### ISSUE TITLE
Consecutive page calls

### ISSUE THREAD

**Issue by shroom24** [mindshape-GmbH/mindshape_cookie_consent#5]
Hello,

so the EventListener gets fired when the user agrees to the options form. But how about finding out which options have been consented to in consecutive page calls? Do I need to read the cookie options myself or is there a Javascript object?

**Comment by featdd** [comment]
Hi @shroom24,

if you made your consent and load another page the event will be dispatched immidiatly.
In the event.detail property you'll find the consents made by the user.
You may have a look into the [documentation](https://docs.typo3.org/p/mindshape/mindshape-cookie-consent/1.0/en-us/Developer/Index.html#the-cookie-consent-event-listener).

Greetings
Daniel
