### ISSUE TITLE
Cannot add override labels with new language

### ISSUE THREAD

**Issue by gf-luka** [mindshape-GmbH/mindshape_cookie_consent#50]
Unfortunately, translations of labels do not work. I cannot translate the two labels "imprint" and "Datapolicy" in the Consent-Modal.

I need Spanish labels in the plugin. Unfortunately, I can neither add Spanish labels via _LOCALLANG nor via locallangXMLOverride.

```
plugin.tx_mindshapecookieconsent._LOCAL_LANG.es {
  label.imprint = Aviso legal
  label.datapolicy = Política de privacidad
}
```

or

```
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['es']
    ['EXT:mindshape_cookie_consent/Resources/Private/Language/es.locallang.xlf'][]
        = 'EXT:agaplesion_template/Resources/Extensions/mindshape_coockieconsent/Language/es.locallang.xlf';
```

Greetings, Gianni

**Comment by featdd** [comment]
Hi @gf-luka,

thanks for the hint, I will have to test this by myself and see if this a bug in the extension or the core, [by documentation](https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Localization/ManagingTranslations.html) it seems okay how you did it.

I'll just need some time to give you the feedback.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @gf-luka,

sorry for the late response, I tried this by myself now and could not find an error.

I registered the override XLIFF file like this:

`$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:mindshape_cookie_consent/Resources/Private/Language/locallang.xlf'][] = 'EXT:website/Resources/Private/Language/de.mindshape_cookie_consent.xlf';`
(As the array key, even you use another language, you still reference the default translation file)

In the translation file itself you have to use the "target" tag, in the default only you use the "source", see my example:

```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
  <file source-language="en" target-language="de" datatype="plaintext" original="EXT:mindshape_cookie_consent/Resources/Private/Language/locallang" product-name="mindshape_cookie_consent">
    <header/>
    <body>
      <trans-unit id="label.imprint">
        <target>Übersetzungstest</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

You can find further information in the [documentation](https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Localization/ManagingTranslations.html).

The "_LOCAL_LANG" feature does not work in some places, like for the translate viewhelper, see also [here](https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/HowTo/Localization/TypoScript.html#changing-localized-terms-using-typoscript).

Greetings
Daniel
