### ISSUE TITLE
Problem with current PHP 8.3.2 version

### ISSUE THREAD

**Issue by karlalbertknapp** [mindshape-GmbH/mindshape_cookie_consent#51]
Hi Daniel,

I use the mindshape_cookie_consent extension with TYPO3 v12.4.11 and PHP 8.3.2 and I get the following error message, when I try to execute composer update:
_- mindshape/mindshape-cookie-consent v3.1.2 requires php >=8.0 <=8.3 -> your php version (8.3.2) does not satisfy that requirement._

When I set the PHP version to 8.3.0 it works. Did you indicate problems with PHP 8.3.2 or is it just an adjustment in the composer.json file?

Cheers
Christopher

**Comment by featdd** [comment]
Hi @karlalbertknapp,

this is strange, as <=8.3 should allow all 8.3.X versions and I didn't encounter this issue yet.
Have you set some specific version in your composer.json in "config -> platform -> php"?

I'll have to test this myself again, you may please have an extra log at the output of your composer update!?

Greetings
Daniel

**Comment by featdd** [comment]
@karlalbertknapp I will try to test this myself on the weekend.

I don't know if this is a misunderstanding or a strange behaviour from composers version parser
If I test this in tools like this it works: https://jubianchi.github.io/semver-check/#/%3E%3D8.0%20%3C%3D8.3/8.3.2

The constraint "~8.0 <8.4" seems to work, can you give me feedback if it worked for you too?

I will prepare a patch next week after I made some testing myself.

Greetings
Daniel

**Comment by karlalbertknapp** [comment]
Hi Daniel,

I will test it and let you know if it works for me as well.

Grettings 
Christopher

**Comment by featdd** [comment]
@karlalbertknapp I fixed this here: 4574c9a9b9c414fc87a92a7c0e6ffb02258e28bc

seems like I had config.platform set on my other machine and didn't got the error displayed...
I will prepare an update next week with some other fixes.

Greetings
Daniel

**Comment by karlalbertknapp** [comment]
Hi Daniel,

thank you very much for your fast action. 

Greetings 
Christopher
