### ISSUE TITLE
Disable Plugin for new site with root directory... 

### ISSUE THREAD

**Issue by quadronet** [mindshape-GmbH/mindshape_cookie_consent#52]
Hello, i have create a second site in backend, new root site with own domain. 

But the plugin is shown on frontend. 

how can i disable the plugin for the new site ?

**Comment by featdd** [comment]
Hi @quadronet,

If you have a look at the [documentation](https://docs.typo3.org/p/mindshape/mindshape-cookie-consent/3.1/en-us/Developer/TypoScript.html) you can use the TypoScript setting "disableConsent" to disable the consent for pages.


Greetings
Daniel
