### ISSUE TITLE
Error on Statistics View 2

### ISSUE THREAD

**Issue by msollmann** [mindshape-GmbH/mindshape_cookie_consent#53]
Could not re-open "Error on Statistics View ", so I created an new one. Description here: https://github.com/mindshape-GmbH/mindshape_cookie_consent/issues/1

**Comment by featdd** [comment]
Hi @msollmann,

this is solved now here: 0ca67c787a23570244dc1e3e109ad0c0ad31a8db

Greetings
Daniel
