### ISSUE TITLE
Error: Typed property ...Configuration::$cookieCategories must not be accessed before initialization

### ISSUE THREAD

**Issue by devxpoint** [mindshape-GmbH/mindshape_cookie_consent#54]
TYPO3 11.5.13 with PHP 8.1 and composer mode
-> installedmindshape_cookie_consent 3.2.2.
-> add a configuration on root page (as usual)

**I get in FE and BE errors, very similar:**

**Frontent:**

`Typed property Mindshape\MindshapeCookieConsent\Domain\Model\Configuration::$necessaryCookieOptions must not be accessed before initialization
in /html/typo3-2022/public/typo3conf/ext/mindshape_cookie_consent/Classes/Domain/Model/Configuration.php line 235

     * @return \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\Mindshape\MindshapeCookieConsent\Domain\Model\CookieOption>
     */
    public function getNecessaryCookieOptions(): ObjectStorage
    {
        return $this->necessaryCookieOptions;
    }

    /**
     * @param \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\Mindshape\MindshapeCookieConsent\Domain\Model\CookieOption> $necessaryCookieOptions

at Mindshape\MindshapeCookieConsent\Domain\Model\Configuration->getNecessaryCookieOptions()
in /html/typo3-2022/public/typo3conf/ext/mindshape_cookie_consent/Classes/Domain/Model/Configuration.php line 386`

**Backend on using the statistics module:**

`Typed property Mindshape\MindshapeCookieConsent\Domain\Model\Configuration::$cookieCategories must not be accessed before initialization
in /html/typo3-2022/public/typo3conf/ext/mindshape_cookie_consent/Classes/Domain/Model/Configuration.php line 347

     * @return \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\Mindshape\MindshapeCookieConsent\Domain\Model\CookieCategory>
     */
    public function getCookieCategories(): ObjectStorage
    {
        return $this->cookieCategories;
    }

    /**
     * @param \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\Mindshape\MindshapeCookieConsent\Domain\Model\CookieCategory> $cookieCategories

at Mindshape\MindshapeCookieConsent\Domain\Model\Configuration->getCookieCategories()
in /html/typo3-2022/public/typo3conf/ext/mindshape_cookie_consent/Classes/Controller/Backend/StatisticController.php line 178`

What can be the reason?

I cleared cache and used dump autoload to ensure, everything is ok.

**Comment by featdd** [comment]
Hi @devxpoint,

I just had a look but could'nt reproduce this, but I use the more latest version of TYPO3 11.5.38.
Can you try update your TYPO3? This is recommended anyway due to security updates.

Greetings
Daniel

**Comment by devxpoint** [comment]
Hallo Daniel,

es lag tatsächlich an TYPO3. Ein Update auf die neueste 11er Version hat es gelöst.
Danke

André

**Comment by featdd** [comment]
Hi @devxpoint,

thanks for the reply, I will increase the minimum version of the extension in the next update.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @devxpoint,

I just tried to figure out why this happens but have no clue, seems like the constructor wasn't called properly, maybe some property mapper magick where the class gets mocked instead of instanciated did not work properly.

In version 11.5.14 it works properly again, nevertheless I just increased the minimal v11 requirement to the latest version.

See: 509b8a4e3f77b1e8610f0f527b275b0030f83f41

Greetings
Daniel
