### ISSUE TITLE
Required argument "consent" is not set for Mindshape\ ...

### ISSUE THREAD

**Issue by kurtwithslc** [mindshape-GmbH/mindshape_cookie_consent#6]
got this error:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "consent" is not set for Mindshape\MindshapeCookieConsent\Controller\ConsentController->consent. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /html/typo3/typo3_src-10.4.9/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php in line 960. ...

Typo3 10.4.9, Mindshape 1.0.4

**Comment by featdd** [comment]
Hi @kurtwithslc,

when did you have this exception, in the ajax request when submitting the consent?
Do you use the javascript provided by the extension or a custom solution?

Any more details would help, so I can reproduce this and help you or push a an update if needed.

Greetings
Daniel

**Comment by kurtwithslc** [comment]
Hi Daniel,

here is the full error info for one example:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "consent" is not set for Mindshape\MindshapeCookieConsent\Controller\ConsentController->consent. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /html/typo3/typo3_src-10.4.9/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php in line 960. Requested URL: https://www.knote-weiden.de/?tx_mindshapecookieconsent_consent%%5Baction%%5D=consent&tx_mindshapecookieconsent_consent%%5Bcontroller%%5D=Consent&type=8641&cHash=d8f9bde608dac4111a3495be60d1d8bf

The exception is found in typo3 protokoll

I use no special javascript - installed cookie consent, added impressum and datenschutz link (i have a multi domain installation), thats it



Beste Grüsse
Kurt Knote

Mühlweg 39
D-92637 Weiden
kurt.knote@t-online.de

**Comment by featdd** [comment]
Hi @kurtwithslc,

I just checked your site url, even though there are still no cookie options it seems everything is working fine!?

Are you still in development?
Maybe there was an error and the javascript doesn't worked properly.

I would'nt put further effort in this for now, if you can reproduce this and can send me more details I'll try to help you.

Greetings
Daniel
