### ISSUE TITLE
necessaryCookieOption.identifier is empty

### ISSUE THREAD

**Issue by KreativeKrise** [mindshape-GmbH/mindshape_cookie_consent#7]
For the checkboxes the id will be generated by `{idPrefix}-cookieoption-{necessaryCookieOption.identifier}`. But `{necessaryCookieOption.identifier}` is empty, which will lead to duplicated id values, if you have more than 1 necessary cookie.

Maybe it's better to use `{idPrefix}-cookieoption-{necessaryCookieOption.uid}` instead. And to unify it, `{idPrefix}-cookieoption-{cookieOption.uid}` could be used for the optional cookie checkboxes.

**Comment by featdd** [comment]
Hi @KreativeKrise,

thanks for the hint, I fixed that in a212d07de366051bd85051388d65b509110a8432 but I didn't unified it with the normal options because they maybe already used in custum StyleSheets or JavaScript.

An Update is also uploaded to TER.

Greetings
Daniel
