### ISSUE TITLE
Remove the type="text/css" attribute

### ISSUE THREAD

**Issue by quadronet** [mindshape-GmbH/mindshape_cookie_consent#8]
Hey, please remove the type attribute from javascript:

**Comment by featdd** [comment]
Hi @quadronet,

could you please provide further details!?

Greetings
Daniel

**Comment by quadronet** [comment]
Yes i can, in your RenderPreProcessHook.php you use the type attribute for javascript: 
$pageRenderer->addHeaderData('<script type="text/javascript"

https://validator.w3.org/ show an error: 

Warning: The type attribute is unnecessary for JavaScript resources.
s.de/"/><script type="text/javascript" data-ignore="1">

**Comment by featdd** [comment]
Thats strange as it is valid html and also the typo3 core sets the type attribute by default.
I'll do some research for that, in the meantime don't panic, its a lax warning browsers pagespeed etc. won't be angry about it.

**Comment by featdd** [comment]
@quadronet as of html 5.2 the type should be omitted, so will remove it in the next update.

See:
https://stackoverflow.com/questions/4195427/is-the-type-attribute-necessary-for-script-tags/4195504#4195504
https://www.w3.org/TR/html52/semantics-scripting.html#element-attrdef-script-type

**Comment by featdd** [comment]
solved in dec2479e92aa3d0da8dfafcfcf2af876605740df

**Comment by flonor1** [comment]
Hy @featdd 
just saw that when embedding the JS type="text/javascript" is still present. Unfortunately I didn't find out where this comes from (didn't find it anywhere in the extension, maybe it comes from TYPO3?).
Is it still possible to remove this, since W3C shows a warning.
